[package]
name = "xyk_pool"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1.0"
dotenv = "0.15"
miden-assembly = "0.25"
miden-client = { version = "0.15.3", features = ["testing", "tonic"] }
miden-client-sqlite-store = { version = "0.15.3" }
miden-core = "0.25"
miden-protocol = { version = "0.15.3", default-features = false, features = [
  "testing",
] }
miden-standards = { version = "0.15.3", default-features = false }
miden-tx = "0.15.3"
rand = { version = "0.9" }
rand_chacha = "0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
tokio = { version = "1.46", features = [
  "fs",
  "macros",
  "net",
  "rt-multi-thread",
] }
toml = "0.9.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
miden-processor = "=0.23.5"
